# Generated by Django 2.1.7 on 2019-03-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_auto_20190305_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
